# -*- coding: utf-8 -*-
"""PRACTICE_EX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EI1fA8A2xAnO-3iTUJsTVynw1C4DXcHf

#Libraries
"""

import streamlit as st
import pandas as pd
import joblib

# Load model
model = joblib.load("beer_prediction_model.pkl")

st.title("🍺 Beer Servings Prediction App")

# Country list
country = st.text_input("Country")

beer = st.number_input(
    "Beer Servings",
    min_value=0,
    max_value=500,
    value=100
)

spirit = st.number_input(
    "Spirit Servings",
    min_value=0,
    max_value=500,
    value=50
)

wine = st.number_input(
    "Wine Servings",
    min_value=0,
    max_value=500,
    value=50
)

continent = st.selectbox(
    "Continent",
    ["Africa",
     "Asia",
     "Europe",
     "North America",
     "Oceania",
     "South America"]
)

input_data = pd.DataFrame({
    "country":[country],
    "beer_servings":[beer],
    "spirit_servings":[spirit],
    "wine_servings":[wine],
    "continent":[continent]
})

if st.button("Predict"):

    prediction = model.predict(input_data)

    st.success(
        f"Predicted Total Litres of Pure Alcohol: {prediction[0]:.2f}"
    )

